# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_name", models.CharField(max_length=255, verbose_name="리포트명")),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        help_text="업로드 시 MinIO에 저장되고 URL이 report_url에 저장됩니다.",
                        null=True,
                        upload_to="reports/",
                        verbose_name="리포트 파일",
                    ),
                ),
                (
                    "report_url",
                    models.URLField(
                        blank=True,
                        help_text="MinIO에 적재된 파일의 URL (파일 업로드 시 자동 저장)",
                        max_length=500,
                        verbose_name="MinIO 적재 URL",
                    ),
                ),
            ],
            options={
                "db_table": "report",
                "verbose_name": "리포트",
                "verbose_name_plural": "리포트",
            },
        ),
    ]
