# Generated by Django 6.0.2

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_report_report_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name="생성일시"),
            preserve_default=False,
        ),
    ]
