# Generated by Django 6.0.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_report_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="storage_key",
            field=models.CharField(blank=True, help_text="MinIO 삭제 시 사용하는 객체 키", max_length=500, verbose_name="MinIO 객체 키"),
        ),
        migrations.AddField(
            model_name="report",
            name="person",
            field=models.ForeignKey(blank=True, db_column="person_id", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reports", to=settings.AUTH_USER_MODEL, verbose_name="로그인 사용자"),
        ),
    ]
